FROM resin/%%RESIN_MACHINE_NAME%%-golang as builder
WORKDIR /go/src/hello-world
COPY main.go ./
RUN CGO_ENABLED=0 go install -a -tags netgo -ldflags '-extldflags "-static"'

FROM resin/scratch
COPY --from=builder /go/bin/hello-world /hello-world
COPY --from=builder /etc/ssl/certs/ /etc/ssl/certs
CMD ["/hello-world"]
